import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { dark, neobrutalism } from '@clerk/themes';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <ClerkProvider>
      <body>{children}</body>
    </ClerkProvider>
<<<<<<< HEAD:frontend/app/layout.tsx

=======
     </html>
>>>>>>> backend:frontend/src/app/layout.js
  );
}
