import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { dark, neobrutalism } from '@clerk/themes';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider >
      <html lang="en">
      <body>{children}</body>
      </html>
    </ClerkProvider>

  );
}